#+AUTHOR:    Anton S. Kosinov
#+TITLE:     Python Desing Patterns
#+SUBTITLE:  exhaustive list
#+EMAIL:     a.s.kosinov@gmail.com
#+LANGUAGE: en
#+STARTUP: showall

* Intro

** Foreword
   #+BEGIN_QUOTE
   Controlling complexity is the essence of computer programming.
   #+BEGIN_EXPORT html
   <p align="right">
   Brian Kernighan
   </p>
   #+END_EXPORT

   All problems in computer science can be solved by another level
   of indirection (abstraction).
   #+BEGIN_EXPORT html
   <p align="right">
   David Wheeler
   </p>
   #+END_EXPORT
   #+END_QUOTE
** Intention
   The aim and passion of this repository is a knowledge taxonomy.
** Target audience
   Anybody who are curious in studying and appreciate clarity simultaneously.
** Contribution
   Please feel free to do any corrections, amendments or suggestions.
   /Keep clear, please./
* Overview
** Python3 only
   It is a contemporary version and seems it is used to become the one
   very soon.
** Methodology
*** Brief survey
*** Several examples
*** Test suite
* Structure
  #+BEGIN_SRC shell :results output :exports results
  tree -I '*~|#*|*.pyc|__pycache__'
  #+END_SRC

  #+RESULTS:
  #+begin_example
  .
  ├── patterns
  │   ├── behavioral
  │   │   └── README.org
  │   ├── creational
  │   │   ├── factory
  │   │   │   ├── pet_factory.py
  │   │   │   ├── README.org
  │   │   │   ├── test_pet_factory.py
  │   │   │   ├── test_weapon_factory.py
  │   │   │   └── weapon_factory.py
  │   │   └── README.org
  │   ├── README.org
  │   └── structural
  │       └── README.org
  └── README.org

  5 directories, 10 files
#+end_example

* Corollary

